FROM node:20.14-alpine as builder

WORKDIR /front

COPY ./front ./

RUN npm install

RUN npx patch-package

RUN npm run build

FROM node:20.14-alpine

COPY --from=builder /front/build ./build

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "build"]