FROM node:20.14-alpine

WORKDIR /app

COPY /front/package.json .

RUN npm install

RUN npm i -g serve

COPY /front .

RUN npx patch-package

RUN npm run build

EXPOSE 3000

CMD [ "serve", "-s", "front/build" ]