version: "3.8"
services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--loadmodule", "/opt/redis-stack/lib/redisearch.so", "--loadmodule", "/opt/redis-stack/lib/rejson.so"]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  flower:
    image: mher/flower
    command: ["python", "-m", "flower", "--broker=redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/0", "flower"]
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy

  worker:
    container_name: worker
    restart: always
    build:
      context: ././
      dockerfile: Dockerfile
    expose:
      - 7777
    ports:
      - "7777:7777"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    command: "playwright install chrome && celery -A src.celery_worker worker --loglevel=INFO"

volumes:
  redis_data:
