version: "3.8"
services:
  worker:
    container_name: worker
    restart: always
    build:
      context: ././
      dockerfile: Dockerfile
    expose:
      - 7777
    ports:
      - "7777:7777"
    volumes:
      - .:/app
    env_file:
      - .env
    command: "playwright install chrome && celery -A src.celery_worker worker --loglevel=INFO"
