version: "3.8"
services:
  worker:
    container_name: worker
    restart: always
    build:
      context: ././
      dockerfile: Dockerfile
    expose:
      - 7777
    ports:
      - "7777:7777"
    volumes:
      - .:/app
    env_file:
      - .env
    command: "celery -A src.celery_worker worker --loglevel=INFO"

  worker-healthcheck:
    container_name: worker-healthcheck
    restart: always
    build:
      context: ././
      dockerfile: Dockerfile-worker-health
    expose:
      - 8001
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    env_file:
      - .env
    command: "uvicorn worker_healthcheck:app --reload --host 0.0.0.0 --port 8001 --log-level debug --use-colors"
