FROM python:3.12-slim-bookworm

WORKDIR /app

RUN pip install fastapi

COPY . /app

CMD ["uvicorn", "worker_healthcheck:app", "--reload", "--host", "0.0.0.0", "--port", "8001", "--log-level", "debug", "--use-colors"]
