"""applications_unique_short_id

Revision ID: c57c92feb0b6
Revises: f236bb9f0c0e
Create Date: 2024-08-04 13:53:22.286979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57c92feb0b6'
down_revision: Union[str, None] = 'f236bb9f0c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'applications', ['short_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='unique')
    # ### end Alembic commands ###
