"""relationship

Revision ID: 95f74e516b36
Revises: 841fe748b40b
Create Date: 2024-05-19 16:24:38.638724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f74e516b36'
down_revision: Union[str, None] = '841fe748b40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'applications', 'users', ['owner_id'], ['id'])
    op.add_column('searches', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'searches', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'searches', type_='foreignkey')
    op.drop_column('searches', 'owner_id')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'owner_id')
    # ### end Alembic commands ###
