"""'relationships'

Revision ID: 841fe748b40b
Revises: d1ae94e71ff4
Create Date: 2024-05-17 19:16:40.187060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841fe748b40b'
down_revision: Union[str, None] = 'd1ae94e71ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'title',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('applications', 'description',
               existing_type=sa.VARCHAR(length=10000),
               nullable=False)
    op.alter_column('applications', 'application_link',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('applications', 'url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('searches', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('searches', 'url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.add_column('users', sa.Column('language_code', sa.String(length=200), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('users', 'language_code')
    op.alter_column('searches', 'url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('searches', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('applications', 'url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('applications', 'application_link',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('applications', 'description',
               existing_type=sa.VARCHAR(length=10000),
               nullable=True)
    op.alter_column('applications', 'title',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###
