"""application

Revision ID: 94e7205884b9
Revises: 90a5c661e4e8
Create Date: 2024-08-10 10:39:43.635176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e7205884b9'
down_revision: Union[str, None] = '90a5c661e4e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'application_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('application_link', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
